name: 'CI Pipeline'

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: 

jobs:
  ci:
    name: 'Build / Test / Report'
    runs-on: 'ubuntu-latest'
    outputs: 
      has_versioning: ${{ steps.check_versioning.outputs.files_exists }}
    steps:
      - name: Checkout Repo
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: 'yarn install --immutable'

      - name: Run CI Tasks
        run: 'yarn moon ci'
        env:
          MOONBASE_SECRET_KEY: ${{ secrets.MOONBASE_SECRET_KEY }}

      - name: Report Moon CI Status
        uses: 'moonrepo/run-report-action@v1'
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Coverage
        run: 'yarn jest --coverage'

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with: 
          directory: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
